name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          echo "Navigating to application directory"
          cd ~/forum-api
          echo "Pulling latest code from GitHub"
          git pull origin main
          echo "Installing dependencies"
          npm install
          echo "Running database migrations"
          npm run migrate up
          echo "Restarting the application using PM2"
          pm2 restart forum-api
          echo "Deployment completed successfully"
